# Generated by Django 5.2.6 on 2025-10-26 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_merchantrequest_commercial_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='api.city', verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='api.governorate', verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='merchantrequest',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.city', verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='merchantrequest',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.governorate', verbose_name='المحافظة'),
        ),
    ]
