# Generated by Django 5.2.6 on 2025-12-02 01:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merchantrequest_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم النشاط')),
                ('icon', models.CharField(blank=True, help_text='اسم الأيقونة من Ionicons', max_length=50, null=True, verbose_name='أيقونة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوع نشاط',
                'verbose_name_plural': 'أنواع الأنشطة',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخطة')),
                ('duration_days', models.IntegerField(verbose_name='المدة بالأيام')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر (ريال يمني)')),
                ('estimated_views', models.CharField(blank=True, help_text='مثال: 1000-1500', max_length=50, null=True, verbose_name='المشاهدات المتوقعة')),
                ('features', models.TextField(blank=True, help_text='ميزات الخطة (كل ميزة في سطر)', null=True, verbose_name='الميزات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('discount_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خطة إعلانية',
                'verbose_name_plural': 'الخطط الإعلانية',
                'ordering': ['order', 'duration_days'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('alkremi', 'الكريمي'), ('alomgy', 'العمقي'), ('cac', 'بنك التسليف'), ('tadhamon', 'بنك التضامن'), ('other', 'أخرى')], max_length=50, verbose_name='البنك')),
                ('account_name', models.CharField(max_length=255, verbose_name='اسم الحساب')),
                ('account_number', models.CharField(max_length=50, verbose_name='رقم الحساب')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr/', verbose_name='QR Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'حساب دفع',
                'verbose_name_plural': 'حسابات الدفع',
                'ordering': ['order', 'bank_name'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مميز حتى'),
        ),
        migrations.CreateModel(
            name='FeaturedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المراجعة'), ('active', 'نشط'), ('rejected', 'مرفوض'), ('expired', 'منتهي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='featured_receipts/', verbose_name='إيصال الدفع')),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الحوالة')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('views_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('favorites_count', models.IntegerField(default=0, verbose_name='الإضافة للمفضلة')),
                ('clicks_count', models.IntegerField(default=0, verbose_name='عدد الضغطات')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_requests', to='api.merchant', verbose_name='التاجر')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_requests', to='api.offer', verbose_name='العرض')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.featuredplan', verbose_name='الخطة')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paymentaccount', verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'طلب إعلان مميز',
                'verbose_name_plural': 'طلبات الإعلانات المميزة',
                'ordering': ['-created_at'],
            },
        ),
    ]
