# Generated by Django 4.2.7 on 2025-11-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_featuredplan_paymentaccount_featuredrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مميز حتى'),
        ),
    ]
