# Generated by Django 5.2.6 on 2025-12-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_businesstype_featuredplan_paymentaccount_and_more'),
        ('api', '0019_offer_featured_until'),
    ]

    operations = [
    ]
