# Generated by Django 5.2.6 on 2025-09-13 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.city', verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='offer',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merchant', verbose_name='التاجر'),
        ),
        migrations.AddField(
            model_name='offerimage',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.offer'),
        ),
    ]
