# Generated by Django 5.2.6 on 2025-09-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='merchants/', verbose_name='الشعار'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='أوقات العمل'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
