# Generated by Django 5.2.6 on 2025-09-25 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_city_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineUsersSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='تفعيل الميزة')),
                ('display_mode', models.CharField(choices=[('full', 'كامل'), ('compact', 'مضغوط'), ('minimal', 'مصغر')], default='full', max_length=20, verbose_name='وضع العرض')),
                ('position', models.CharField(choices=[('bottom', 'وسط الأسفل'), ('bottom-left', 'يسار الأسفل'), ('bottom-right', 'يمين الأسفل')], default='bottom', max_length=20, verbose_name='موضع العداد')),
                ('color_scheme', models.CharField(choices=[('dynamic', 'ديناميكي'), ('green', 'أخضر'), ('blue', 'أزرق'), ('purple', 'بنفسجي'), ('custom', 'مخصص')], default='dynamic', max_length=20, verbose_name='نظام الألوان')),
                ('custom_color', models.CharField(blank=True, max_length=7, null=True, verbose_name='لون مخصص')),
                ('opacity', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1.0)], verbose_name='الشفافية')),
                ('show_activity_status', models.BooleanField(default=True, verbose_name='عرض حالة النشاط')),
                ('show_mini_chart', models.BooleanField(default=True, verbose_name='عرض الرسم البياني')),
                ('show_pulse_animation', models.BooleanField(default=True, verbose_name='عرض النبضات')),
                ('auto_hide_on_scroll', models.BooleanField(default=False, verbose_name='الإخفاء عند التمرير')),
                ('show_only_on_homepage', models.BooleanField(default=False, verbose_name='الصفحة الرئيسية فقط')),
                ('update_interval', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)], verbose_name='معدل التحديث (ثانية)')),
                ('min_users', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الحد الأدنى')),
                ('max_users', models.IntegerField(default=450, validators=[django.core.validators.MinValueValidator(10)], verbose_name='الحد الأقصى')),
                ('peak_hours_start', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='بداية الذروة')),
                ('peak_hours_end', models.IntegerField(default=23, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='نهاية الذروة')),
                ('sound_effects', models.BooleanField(default=False, verbose_name='المؤثرات الصوتية')),
                ('vibration_feedback', models.BooleanField(default=False, verbose_name='الاهتزاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات المتواجدين',
                'verbose_name_plural': 'إعدادات المتواجدين',
            },
        ),
    ]
