# Generated by Django 5.2.6 on 2025-09-26 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_update_position_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المحافظة')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالإنجليزية')),
                ('image', models.ImageField(blank=True, null=True, upload_to='governorates/', verbose_name='صورة المحافظة')),
                ('icon', models.CharField(blank=True, help_text='اسم الأيقونة من Ionicons', max_length=50, null=True, verbose_name='أيقونة')),
                ('color', models.CharField(default='#3b82f6', help_text='لون hex للمحافظة', max_length=7, verbose_name='اللون المميز')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المحافظة')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='عدد السكان')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='api.governorate', verbose_name='المحافظة'),
        ),
    ]
