# Generated by Django 5.2.6 on 2025-10-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_category_offer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='status',
            field=models.CharField(choices=[('قيد المراجعة', 'قيد المراجعة'), ('مقبول', 'مقبول'), ('مرفوض', 'مرفوض')], default='قيد المراجعة', max_length=20, verbose_name='حالة الحساب'),
        ),
    ]
